# rebased/repackaged base image that only updates existing packages
FROM mbentley/ubuntu:20.04
LABEL maintainer="Matt Bentley <mbentley@mbentley.net>"
LABEL org.opencontainers.image.source="https://github.com/mbentley/docker-omada-controller"

RUN apt-get update &&\
  apt-get install --no-install-recommends -y ca-certificates libcurl4 wget &&\
  rm -rf /var/lib/apt/lists/*

RUN cd /tmp &&\
  wget -q https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-4.0.28.tgz &&\
  wget -q https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-4.2.23.tgz &&\
  wget -q https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-4.4.18.tgz &&\
  tar xvf mongodb-linux-x86_64-ubuntu1804-4.0.28.tgz mongodb-linux-x86_64-ubuntu1804-4.0.28/bin/mongod mongodb-linux-x86_64-ubuntu1804-4.0.28/bin/mongo &&\
  tar xvf mongodb-linux-x86_64-ubuntu1804-4.2.23.tgz mongodb-linux-x86_64-ubuntu1804-4.2.23/bin/mongod mongodb-linux-x86_64-ubuntu1804-4.2.23/bin/mongo &&\
  tar xvf mongodb-linux-x86_64-ubuntu1804-4.4.18.tgz mongodb-linux-x86_64-ubuntu1804-4.4.18/bin/mongod mongodb-linux-x86_64-ubuntu1804-4.4.18/bin/mongo &&\
  mv mongodb-linux-x86_64-ubuntu1804-4.0.28/bin/mongod mongod-4.0.28 &&\
  mv mongodb-linux-x86_64-ubuntu1804-4.2.23/bin/mongod mongod-4.2.23 &&\
  mv mongodb-linux-x86_64-ubuntu1804-4.4.18/bin/mongod mongod-4.4.18 &&\
  mv mongodb-linux-x86_64-ubuntu1804-4.0.28/bin/mongo mongo-4.0.28 &&\
  mv mongodb-linux-x86_64-ubuntu1804-4.2.23/bin/mongo mongo-4.2.23 &&\
  mv mongodb-linux-x86_64-ubuntu1804-4.4.18/bin/mongo mongo-4.4.18 &&\
  rm -rf mongodb-*

COPY migrate.sh /

WORKDIR /opt/tplink/EAPController/lib
ENTRYPOINT ["/migrate.sh"]
