name: Sync with upstream and build docker images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # This will run the workflow every day at midnight

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Pull changes from upstream
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "<>"
        git remote add upstream git@github.com:mbentley/docker-omada-controller.git
        git fetch upstream
        git checkout master
        git merge upstream/master --allow-unrelated-histories || echo "Conflicts occurred during merge, creating a PR instead." && exit 1

    - name: Push changes to master
      run: |
        git push

  build:
    needs: sync
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ['Dockerfile' , 'Dockerfile.chromium' , 'Dockerfile.v3.0.x' , 'Dockerfile.v3.1.x' , 'Dockerfile.v3.2.x' , 'Dockerfile.v3.2.x-arm64' , 'Dockerfile.v3.2.x-armv7l' , 'Dockerfile.v4.x' , 'Dockerfile.v5.x' ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./${{ matrix.dockerfile }}
        push: false

    - name: Create or update branch
      run: |
        BRANCH_NAME=${{ matrix.dockerfile == 'Dockerfile' && 'latest' || matrix.dockerfile }}
        git checkout -b $BRANCH_NAME
        git rm Dockerfile*
        git mv ${{ matrix.dockerfile }} Dockerfile
        git commit -am "Update Dockerfile"
        git push origin $BRANCH_NAME --force
